server:
  port: 8500
  servlet:
    #为了防止一会在服务之间跳转导致Cookie打架（因为所有服务地址都是localhost，都会存JSESSIONID）
    #这里修改一下context-path，这样保存的Cookie会使用指定的路径，就不会和其他服务打架了
    #但是注意之后的请求都得在最前面加上这个路径
    context-path: /sso
spring:
  security:
    oauth2:
      client:
        registration:
#          rainyoauth2:
#            provider: rainyoauth2
#            client-id: client
#            client-secret: secret
#            scope:
#              - openid
#            authorization-grant-type: client_credentials
#            redirect-uri: https://github.com/settings/apps
          github:
            clientId: b34cbb765febbc5bbee2
            clientSecret: 73cf60e5a2aec51c01421e72cad25e22f80a33f5
